/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courier.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bishaldeb
 */
public class recieving extends javax.swing.JFrame {
Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
    /**
     * Creates new form tracking
     */
    public recieving() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter your Order Id:- ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courier/system/home.png"))); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(0, 51, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Current Location", "City", "State", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courier/system/Search.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courier/system/home logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Recieving Oder");

        jLabel4.setText("Select the branch office:-");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Delhi", "Mumbai", "Kolkata", "Chennai", "Bangalore", "Guwahati" }));

        jLabel5.setText("Status-");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In transit", "Recieved", "Recieved at the nearest Center", "Delivered Sucessfully" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, 308, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(jTextField1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       if(jComboBox1.getSelectedIndex()==0)
       {String query ="insert into tracking values("
                        + "'" + jTextField1.getText()+ "',"
                        + "'" + "New Delhi"+ "',"
                        + "'" + "Delhi"+"',"
                        + "'" + "Delhi" +"',"
                        + "'" + jComboBox2.getSelectedItem() +"')" ; 

String qry= "Select * from tracking where tid='"+jTextField1.getText()+"'";
        try {
           
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/courier?useSSL=false","root","");
            
            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            stmt.executeQuery(qry);
 
            while (rs.next()) {
                //String TrkId = rs.getString("tid");
                String location= rs.getString("location");
                String city = rs.getString("city");
                String state = rs.getString("state");
                String status = rs.getString("status");
              
                
                model.addRow(new Object[] {location, city, state, status});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"updated Sucessfully!!");
        }
       }
       else if(jComboBox1.getSelectedIndex()==1)
       {String query ="insert into tracking values("
                        + "'" + jTextField1.getText()+ "',"
                        + "'" + "Mumbai"+ "',"
                        + "'" + "Mumbai"+"',"
                        + "'" + "Maharastra" +"',"
                        + "'" + jComboBox2.getSelectedItem() +"')" ;
                        
        String qry= "Select * from tracking";
        try {
           
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/courier?useSSL=false","root","");
            
            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            stmt.executeQuery(qry);
 
            while (rs.next()) {
                //String TrkId = rs.getString("tid");
                String location= rs.getString("location");
                String city = rs.getString("city");
                String state = rs.getString("state");
                String status = rs.getString("status");
              
                
                model.addRow(new Object[] {location, city, state, status});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"updated Sucessfully!!");
        }
       }
       else if(jComboBox1.getSelectedIndex()==2)
       {String query ="insert into tracking values("
                        + "'" + jTextField1.getText()+ "',"
                        + "'" + "Kolkata"+ "',"
                        + "'" + "Kolkata"+"',"
                        + "'" + "West Bengal" +"',"
                        + "'" + jComboBox2.getSelectedItem() +"')" ;
                        
        String qry= "Select * from tracking";
        try {
           
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/courier?useSSL=false","root","");
            
            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            stmt.executeQuery(qry);
 
            while (rs.next()) {
                //String TrkId = rs.getString("tid");
                String location= rs.getString("location");
                String city = rs.getString("city");
                String state = rs.getString("state");
                String status = rs.getString("status");
              
                
                model.addRow(new Object[] {location, city, state, status});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"updated Sucessfully!!");
        }
       }
       else if(jComboBox1.getSelectedIndex()==3)
       {String query ="insert into tracking values("
                        + "'" + jTextField1.getText()+ "',"
                        + "'" + "Chennai"+ "',"
                        + "'" + "Chennai"+"',"
                        + "'" + "Tamil Nadu" +"',"
                        + "'" + jComboBox2.getSelectedItem() +"')" ;
                        
        String qry= "Select * from tracking";
        try {
           
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/courier?useSSL=false","root","");
            
            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            stmt.executeQuery(qry);
 
            while (rs.next()) {
                //String TrkId = rs.getString("tid");
                String location= rs.getString("location");
                String city = rs.getString("city");
                String state = rs.getString("state");
                String status = rs.getString("status");
              
                
                model.addRow(new Object[] {location, city, state, status});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"updated Sucessfully!!");
        }
       }
       else if(jComboBox1.getSelectedIndex()==4)
       {String query ="insert into tracking values("
                        + "'" + jTextField1.getText()+ "',"
                        + "'" + "Bangalore"+ "',"
                        + "'" + "Bangalore"+"',"
                        + "'" + "Karnataka" +"',"
                        + "'" + jComboBox2.getSelectedItem() +"')" ;
                        
        String qry= "Select * from tracking";
        try {
           
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/courier?useSSL=false","root","");
            
            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            stmt.executeQuery(qry);
 
            while (rs.next()) {
                //String TrkId = rs.getString("tid");
                String location= rs.getString("location");
                String city = rs.getString("city");
                String state = rs.getString("state");
                String status = rs.getString("status");
              
                
                model.addRow(new Object[] {location, city, state, status});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"updated Sucessfully!!");
        }
       }
       else if(jComboBox1.getSelectedIndex()==5)
       {String query ="insert into tracking values("
                        + "'" + jTextField1.getText()+ "',"
                        + "'" + "Guwahati"+ "',"
                        + "'" + "Guwahati"+"',"
                        + "'" + "Assam" +"',"
                        + "'" + jComboBox2.getSelectedItem() +"')" ;
                        
        String qry= "Select * from tracking";
        try {
           
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/courier?useSSL=false","root","");
            
            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            stmt.executeQuery(qry);
 
            while (rs.next()) {
                //String TrkId = rs.getString("tid");
                String location= rs.getString("location");
                String city = rs.getString("city");
                String state = rs.getString("state");
                String status = rs.getString("status");
              
                
                model.addRow(new Object[] {location, city, state, status});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"updated Sucessfully!!");
        }
       }
        
        int rows = model.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                model.removeRow(0);
            }
        }
        
        String query = "SELECT * FROM tracking where tid="+"'"+jTextField1.getText()+"';";
        try {
           
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/courier","root","");
            
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
 
            while (rs.next()) {
                String TrackId = rs.getString("tid");
                String location = rs.getString("location");
                String city = rs.getString("city");
                String state = rs.getString("state");
                String status = rs.getString("status");

                
                model.addRow(new Object[] {location, city, state, status});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recieving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recieving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recieving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recieving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recieving().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
